apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcpsm
  namespace: monitoring
spec:
  provider:
    gcpsm:
      projectID: etl-demo-482811
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: monitoring-secrets-sa
